# Generated by Django 4.1.7 on 2023-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PNYNE', '0002_remove_task_tags_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='PNYNE.tag'),
        ),
    ]
